kind: pipeline
type: ssh
name: default

server:
  host: vps603346.ovh.net
  user: mita
  password:
    from_secret: password

steps:
- name: greeting
  commands:
  - echo "hello world"
  - cp ./README.md ~/README.md
  - ls -la
  
  trigger:
    branch:
    - develop
    event:
    - push
